// Scene nav — a left-edge column of scene thumbnail cards, the lab's one
// piece of shared navigation: light card stock against the scenes, one
// screencap per advertised scene.
//
// App.tsx owns which scenes are advertised and how a selection reaches the
// URL; this module owns only the markup. It positions itself (`fixed`), so
// the render site inside a scene stays cosmetic — same contract as the
// chips strip it replaces. Each card shows a screencap of its scene
// (regenerated by `npm run thumbs` in apps/lab) and links to the scene's
// folder on GitHub so a visitor can read how the demo was made.
//
// `active` is a plain string rather than one of `scenes`: unlisted scenes
// are still routable by URL, and the nav simply shows no lit card then.

const GITHUB_SCENES = 'https://github.com/petekp/munari/tree/main/apps/lab/src/scenes'

function GitHubMark() {
  return (
    <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z" />
    </svg>
  )
}

interface SceneNavProps<T extends string> {
  scenes: readonly T[]
  active: string
  onSelect: (id: T) => void
}

export function SceneNav<T extends string>({ scenes, active, onSelect }: SceneNavProps<T>) {
  return (
    // pointer-events-auto: some render sites (the room scenes' hud) are
    // pointer-events:none, and the nav must stay clickable from inside them.
    // z-[150]: above the page scenes' full-viewport overlay canvases (knobs
    // mounts at 50, genie at 100 — knobs' keeps pointer events for its dials,
    // so anything below it is unclickable), below the tuning panels at 200.
    <nav className="pointer-events-auto fixed left-4 top-1/2 z-[150] flex -translate-y-1/2 flex-col gap-2.5">
      {scenes.map((id) => (
        // Nested radii: card 16px minus 6px padding leaves 10px for the image,
        // so the two curves stay concentric.
        <div
          key={id}
          className={`w-32 rounded-2xl border bg-[#f2f0e4]/95 p-1.5 shadow-md backdrop-blur transition-colors ${
            active === id ? 'border-[#e8402a]' : 'border-black/10 hover:border-black/30'
          }`}
        >
          <button
            type="button"
            onClick={() => onSelect(id)}
            aria-label={id}
            aria-current={active === id ? 'page' : undefined}
            className="relative block w-full overflow-hidden rounded-[10px]"
          >
            <img
              src={`/thumbs/${id}.jpg`}
              alt=""
              className="block aspect-video w-full object-cover"
            />
            {/* An inset box-shadow on the <img> itself would paint beneath the
                image content, so the edge line is a separate overlay. */}
            <span className="pointer-events-none absolute inset-0 rounded-[10px] shadow-[inset_0_0_0_1px_rgba(20,20,15,0.14)]" />
          </button>
          <div className="flex items-center justify-between px-1 pb-0.5 pt-1.5">
            <button
              type="button"
              onClick={() => onSelect(id)}
              tabIndex={-1}
              className={`text-sm font-semibold capitalize tracking-wide ${
                active === id ? 'text-[#e8402a]' : 'text-black/70 hover:text-black'
              }`}
            >
              {id}
            </button>
            <a
              href={`${GITHUB_SCENES}/${id}`}
              target="_blank"
              rel="noreferrer"
              aria-label={`${id} source on github`}
              className="text-black/30 hover:text-black"
            >
              <GitHubMark />
            </a>
          </div>
        </div>
      ))}
    </nav>
  )
}
